accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name = 'register'),
    path('profile/', views.profile, name='profile'),
    path('modifprofile/<id>', views.modifprofil, name = 'modifprofil'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('skeditor/', include('ckeditor_uploader.urls')),
    path('', include('pages.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('contact/', include('contact.urls')),
    path('events/', include('events.urls')),
    path('note/', include('note.urls')),
    path('pwd/', include('pwd.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

events/urls.py
from django.urls import path
from . import views

app_name = 'events'

urlpatterns = [
    path('', views.event, name = 'events'),
    path('<int:pk>/', views.detail_event, name = 'detail_events'),
    path('create_event/', views.create_event, name = 'create_event'),
    path('calendar/', views.calendar_view, name = 'calendar'),
    path('calendar/<int:year>/<str:month>/', views.calendar_view, name = 'calendar'),
    
]

pages/urls.py
from django.urls import path, include

from .views import HomePageView, ContactPageView

app_name = 'pages'

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('accounts/', include('accounts.urls')),
]

pwd/urls.py
from django.urls import path
from . import views

app_name = 'pwd'

urlpatterns = [
    path('generator/', views.generator, name = 'generator'),
    
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <title>{% block title %} NotePad{% endblock title %} </title>
<!-- Bootstrap Icons--> 
         <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <link rel="icon" type="{% static 'images/x-icon' %}" href="images/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />        
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel="stylesheet">
<!-- Core theme CSS (includes Bootstrap)-->
        <link rel="stylesheet" href="{% static 'css/styles.css' %}"  /> 
    </head>

    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top py-2" id="mainNav">
            <div class="container px-4 px-lg-5">
            
                {% if user.is_authenticated %}
                        <a class="navbar-brand" href="{% url 'logout' %}">Déconnection</a>
                        <a class="navbar-brand" href="{% url 'accounts:profile' %}">Profil</a>
                {% else %}
                        <a class="navbar-brand" href="{% url 'login' %}">Me connecter</a>
                        <a class="navbar-brand" href="{% url 'accounts:register' %}">M'inscrire </a>
                {% endif %}
                
     <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto my-2 my-lg-0">
                        <li class="nav-item"><a class="nav-link" href={% url 'pages:home' %}>Acceuil</a></li>
                        
                        

                        {% if user.is_authenticated %}
                                <li class="nav-item dropdown">  
                                        <a class="nav-link dropdown-toggle" href="" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="true">
                                                Mes Notes</a>
                                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                                         <li><a class="dropdown-item" href="{% url 'note' %}">Note</a></li> 
                                                        <li><a class="dropdown-item" href="{% url 'add_note' %}">Nouvelle Note</a></li>
                                                </ul>
                                        </li>
                                        <li class="nav-item dropdown">
                                        <a class="nav-link dropdown-toggle" href="" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="true">
                                                PasswordBank</a>
                                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                                         <li><a class="dropdown-item" href="#">Ma banque</a></li> 
                                                        <li><a class="dropdown-item" href="#">Generateur</a></li>
                                                </ul>
                                        </li>
                                        <li class="nav-item dropdown">
                                                <a class="nav-link dropdown-toggle" href="" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="true">
                                                        Mon Calendrier</a>
                                                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                                                <li><a class="dropdown-item" href="{% url 'events:events' %}">Mes Évènements</a></li> 
                                                                <li><a class="dropdown-item" href="{% url 'events:create_event' %}">Ajouter un évènements</a></li>
                                                                <li><a class="dropdown-item" href="{% url 'events:calendar' %}">Calendrier</a></li>
                                                        </ul>
                                                </li>

                        {% endif %}
                        
                        <li class="nav-item">
                                <a class="nav-link " href="{% url 'contact' %}">Contact</a>
                        </li>

                    </ul>
                        <form class="d-flex mx-auto">
                                <input class="form-control me-1" type="search" placeholder="Search" aria-label="Search">
                                <button class="btn btn-outline-light" type="submit">Search</button> 
                        </form>
                </div>
                       

            </div>

                
        </nav>
        
        <header class="masthead">
            <div class="container-ms-auto my-2 my-lg-0">

    {% block content %}

    {% endblock content %}

            </div>
        </header>
<!-- Footer-->
        <footer class="bg-light py-5">
            <div class="container px-4 px-lg-5"><div class="small text-center text-muted">Copyright &copy; 2021 - Olivier Boutet</div></div>
        </footer>
        {% block bottom-scripts %}
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
<!-- SimpleLightbox plugin JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.js"></script> 
<!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
<!-- * *                               SB Forms JS                               * *-->
<!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
        {% endblock bottom-scripts %}

    </body>
</html>